const FALLBACK_CONFIG_GROUPS = [
  {
    id: "live",
    title: "直播监听",
    description: "B站房间、弹幕后端、缓存和注入。",
    keys: [
      "bilibili_enabled",
      "bilibili_type",
      "bilibili_room_id",
      "part_id",
      "area_id",
      "bilibili_web_backend",
      "laplace_event_bridge_url",
      "laplace_event_bridge_token",
      "bilibili_sessdata",
      "bili_live_inject_enabled",
      "bili_live_inject_max_events",
      "bili_live_cache_size",
      "bili_live_log_events",
      "bili_live_debug_log",
    ],
  },
  {
    id: "obs",
    title: "OBS 开播控制",
    description: "启动 OBS/L2DStudio、连接 OBS WebSocket、调试场景和二次确认开播。",
    keys: [
      "obs_control_enabled",
      "obs_exe_path",
      "l2dstudio_exe_path",
      "obs_ws_host",
      "obs_ws_port",
      "obs_ws_password",
      "obs_live_scene_name",
      "obs_startup_wait_seconds",
      "obs_debug_start_virtual_camera",
      "obs_allow_stream_start",
    ],
  },
  {
    id: "reply",
    title: "自动回应",
    description: "直播弹幕触发 LLM 回复的频率、模式和提示词。",
    keys: [
      "bili_live_auto_reply_enabled",
      "bili_live_auto_reply_mode",
      "bili_live_auto_reply_session_id",
      "bili_live_auto_reply_cooldown_seconds",
      "bili_live_auto_reply_max_per_minute",
      "bili_live_auto_reply_min_events",
      "bili_live_auto_reply_max_events",
      "bili_live_auto_reply_air_guard_enabled",
      "bili_live_auto_reply_air_guard_model_enabled",
      "bili_live_auto_reply_air_guard_threshold",
      "bili_live_auto_reply_max_length",
      "bili_live_auto_reply_force_full_tts",
      "bili_live_auto_reply_sync_tts_subtitle",
      "bili_live_tts_local_playback_enabled",
      "bili_live_reply_identity_mode",
      "bili_live_streamer_identity_from_companion_enabled",
      "bili_live_streamer_display_name",
      "bili_live_auto_reply_system_prompt",
    ],
  },
  {
    id: "memory",
    title: "记忆与陪伴",
    description: "直播记忆、关系网线索、观众画像和下播小结。",
    keys: [
      "live_memory_enabled",
      "live_memory_context_enabled",
      "live_memory_context_max_lines",
      "live_memory_max_items",
      "live_memory_topic_enabled",
      "live_memory_max_topics",
      "live_memory_max_open_threads",
      "live_memory_max_highlights",
      "private_companion_live_context_enabled",
      "private_companion_live_context_max_age_seconds",
      "private_companion_live_context_recent_limit",
      "private_companion_live_context_max_users",
      "private_companion_live_context_include_identity_note",
      "private_companion_relationship_style_context_enabled",
      "private_companion_relationship_style_include_profile",
      "private_companion_relationship_style_include_memories",
      "private_companion_writeback_enabled",
      "private_companion_viewer_activity_enabled",
      "private_companion_viewer_activity_context_enabled",
      "private_companion_auto_register_viewers",
      "private_companion_auto_register_min_events",
      "private_companion_live_state_enabled",
      "private_companion_live_state_cooldown_seconds",
      "private_companion_live_state_duration_hours",
      "private_companion_live_summary_enabled",
    ],
  },
  {
    id: "subtitle",
    title: "打字机字幕",
    description: "OBS overlay 的服务地址、打字速度、样式和文本清理规则。",
    keys: [
      "subtitle_enabled",
      "subtitle_scope",
      "subtitle_host",
      "subtitle_port",
      "subtitle_typing_speed_ms",
      "subtitle_hold_seconds",
      "subtitle_max_length",
      "subtitle_font_size",
      "subtitle_font_weight",
      "subtitle_text_color",
      "subtitle_stroke_color",
      "subtitle_stroke_size",
      "subtitle_cursor_color",
      "subtitle_show_cursor",
      "subtitle_fade_out",
      "subtitle_position",
      "subtitle_padding",
      "subtitle_max_width",
      "subtitle_strip_l2d_tags",
      "subtitle_strip_tts_blocks",
      "subtitle_voice_use_following_plain",
      "subtitle_prefer_chinese_text",
      "subtitle_use_tts_spoken_text",
      "subtitle_strip_html_tags",
    ],
  },
  {
    id: "stage",
    title: "Soullink 与嘴型",
    description: "连续情绪表演、VTS 参数映射和 TTS 嘴型。",
    keys: [
      "soullink_enabled",
      "soullink_mode",
      "soullink_motion_style",
      "soullink_fps",
      "soullink_prompt_intent_enabled",
      "soullink_local_fallback_enabled",
      "soullink_parameter_gain",
      "soullink_body_motion_gain",
      "soullink_vad_decay_rate",
      "soullink_node_path",
      "soullink_vts_mapping",
      "mouth_sync_enabled",
      "mouth_sync_open_parameter",
      "mouth_sync_form_parameter",
      "mouth_sync_fps",
      "mouth_sync_gain",
      "mouth_sync_smoothing",
      "mouth_sync_noise_gate",
      "mouth_sync_form_strength",
      "mouth_sync_mode",
    ],
  },
];

const FALLBACK_CONFIG_SCHEMA = {
  soullink_enabled: { description: "启用 Soullink Emotion 实时表演引擎", type: "bool", default: false },
  soullink_mode: { description: "Soullink 运行模式", type: "string", default: "emotion", options: ["emotion", "full"] },
  soullink_motion_style: { description: "Soullink 动作风格", type: "string", default: "natural", options: ["natural", "lively", "calm", "shy"] },
  soullink_fps: { description: "Soullink 实时帧率", type: "int", default: 20, slider: { min: 5, max: 30, step: 1 } },
  soullink_prompt_intent_enabled: { description: "通过提示词生成 Soullink 情绪意图", type: "bool", default: true },
  soullink_local_fallback_enabled: { description: "缺少情绪意图时使用本地分类", type: "bool", default: false },
  soullink_parameter_gain: { description: "Soullink 表情参数增益", type: "float", default: 1.7, slider: { min: 0.4, max: 5, step: 0.05 } },
  soullink_body_motion_gain: { description: "Soullink 头部与身体动作增益", type: "float", default: 1.6, slider: { min: 0, max: 4, step: 0.05 } },
  soullink_vad_decay_rate: { description: "Soullink 情绪衰减速度", type: "float", default: 0.075, slider: { min: 0, max: 0.2, step: 0.001 } },
  soullink_node_path: { description: "Node.js 路径（可选）", type: "string", default: "" },
  soullink_vts_mapping: { description: "Soullink 到 VTS 参数映射（高级）", type: "text", default: "{}", hint: "请在 Soullink 实时测试台的高级参数校准中编辑" },

  bilibili_enabled: { description: "启用 B站直播功能", type: "bool", default: false },
  bilibili_type: { description: "B站直播监听类型", type: "string", default: "web", options: ["web", "laplace", "open_live"] },
  bilibili_room_id: { description: "B站直播房间号", type: "int", default: 0 },
  part_id: { description: "B站直播父分区 ID", type: "int", default: 0 },
  area_id: { description: "B站直播子分区 ID", type: "int", default: 0 },
  bilibili_web_backend: { description: "B站 Web 弹幕后端", type: "string", default: "builtin", options: ["builtin", "history", "laplace", "blivedm"] },
  laplace_event_bridge_url: { description: "Laplace Event Bridge 地址", type: "string", default: "ws://localhost:9696" },
  laplace_event_bridge_token: { description: "Laplace Event Bridge 密码", type: "string", default: "" },
  bilibili_sessdata: { description: "B站 Cookie / SESSDATA", type: "string", default: "" },
  bili_live_inject_enabled: { description: "向 LLM 注入最近直播弹幕", type: "bool", default: true },
  bili_live_inject_max_events: { description: "每次注入的最大直播事件数", type: "int", default: 8, slider: { min: 1, max: 30, step: 1 } },
  bili_live_cache_size: { description: "直播事件缓存数量", type: "int", default: 80, slider: { min: 10, max: 300, step: 10 } },
  bili_live_log_events: { description: "记录直播事件日志", type: "bool", default: true },
  bili_live_debug_log: { description: "直播协议调试日志", type: "bool", default: false },

  obs_control_enabled: { description: "启用 OBS 开播控制", type: "bool", default: false },
  obs_exe_path: { description: "OBS 程序路径", type: "string", default: "" },
  l2dstudio_exe_path: { description: "L2DStudio 程序路径", type: "string", default: "" },
  obs_ws_host: { description: "OBS WebSocket 地址", type: "string", default: "127.0.0.1" },
  obs_ws_port: { description: "OBS WebSocket 端口", type: "int", default: 4455 },
  obs_ws_password: { description: "OBS WebSocket 密码", type: "string", default: "" },
  obs_live_scene_name: { description: "默认直播场景名", type: "string", default: "" },
  obs_startup_wait_seconds: { description: "启动后等待秒数", type: "int", default: 3, slider: { min: 0, max: 20, step: 1 } },
  obs_debug_start_virtual_camera: { description: "调试时开启 OBS 虚拟摄像机", type: "bool", default: true },
  obs_allow_stream_start: { description: "允许插件开始推流", type: "bool", default: false },

  bili_live_auto_reply_enabled: { description: "启用直播弹幕自动回应", type: "bool", default: false },
  bili_live_auto_reply_mode: { description: "自动回应模式", type: "string", default: "native", options: ["native", "direct"] },
  bili_live_auto_reply_session_id: { description: "自动回应会话ID", type: "string", default: "" },
  bili_live_auto_reply_cooldown_seconds: { description: "自动回应冷却时间", type: "float", default: 12, slider: { min: 3, max: 120, step: 1 } },
  bili_live_auto_reply_max_per_minute: { description: "每分钟最多自动回复", type: "int", default: 6, slider: { min: 0, max: 60, step: 1 } },
  bili_live_auto_reply_min_events: { description: "触发回应最少事件数", type: "int", default: 1, slider: { min: 1, max: 20, step: 1 } },
  bili_live_auto_reply_max_events: { description: "每次参考事件数", type: "int", default: 5, slider: { min: 1, max: 20, step: 1 } },
  bili_live_auto_reply_air_guard_enabled: { description: "启用直播读空气降噪", type: "bool", default: true },
  bili_live_auto_reply_air_guard_model_enabled: { description: "联动陪伴插件读空气模型", type: "bool", default: true },
  bili_live_auto_reply_air_guard_threshold: { description: "直播读空气回应阈值", type: "float", default: 2.5, slider: { min: 0.5, max: 6, step: 0.1 } },
  bili_live_auto_reply_max_length: { description: "自动回应最大长度", type: "int", default: 80, slider: { min: 20, max: 200, step: 5 } },
  bili_live_auto_reply_force_full_tts: { description: "直播自动回应请求语音回复", type: "bool", default: true },
  bili_live_auto_reply_sync_tts_subtitle: { description: "直播 TTS 与打字机同步", type: "bool", default: true },
  bili_live_tts_local_playback_enabled: { description: "直播 TTS 本机播放", type: "bool", default: true },
  bili_live_reply_identity_mode: { description: "直播回复身份模式", type: "string", default: "host", options: ["host", "assistant"] },
  bili_live_streamer_identity_from_companion_enabled: { description: "从陪伴插件读取主要用户直播身份", type: "bool", default: true },
  bili_live_streamer_display_name: { description: "主播显示名覆盖", type: "string", default: "" },
  bili_live_auto_reply_system_prompt: { description: "自动回应系统提示词", type: "text", default: "你是正在直播中的虚拟主播助手。请根据观众最近的弹幕自然回应，语气像实时聊天，不要逐条复读。" },

  live_memory_enabled: { description: "启用直播专用记忆", type: "bool", default: true },
  live_memory_context_enabled: { description: "注入直播专用记忆", type: "bool", default: true },
  live_memory_context_max_lines: { description: "直播记忆上下文行数", type: "int", default: 12, slider: { min: 4, max: 30, step: 1 } },
  live_memory_max_items: { description: "直播记忆条目上限", type: "int", default: 80, slider: { min: 20, max: 300, step: 10 } },
  live_memory_topic_enabled: { description: "记录直播常聊话题", type: "bool", default: true },
  live_memory_max_topics: { description: "直播话题上限", type: "int", default: 80, slider: { min: 20, max: 300, step: 10 } },
  live_memory_max_open_threads: { description: "未完话题上限", type: "int", default: 20, slider: { min: 6, max: 80, step: 2 } },
  live_memory_max_highlights: { description: "直播高光上限", type: "int", default: 40, slider: { min: 10, max: 120, step: 5 } },
  private_companion_live_context_enabled: { description: "联动陪伴插件关系网", type: "bool", default: true },
  private_companion_live_context_max_age_seconds: { description: "群聊线索有效时间", type: "float", default: 900, slider: { min: 30, max: 7200, step: 30 } },
  private_companion_live_context_recent_limit: { description: "每人群聊线索条数", type: "int", default: 3, slider: { min: 1, max: 8, step: 1 } },
  private_companion_live_context_max_users: { description: "最多识别观众数", type: "int", default: 3, slider: { min: 1, max: 8, step: 1 } },
  private_companion_live_context_include_identity_note: { description: "注入身份备注", type: "bool", default: false },
  private_companion_relationship_style_context_enabled: { description: "注入关系称呼风格", type: "bool", default: true },
  private_companion_relationship_style_include_profile: { description: "注入关系画像", type: "bool", default: false },
  private_companion_relationship_style_include_memories: { description: "注入关系重要记忆", type: "bool", default: false },
  private_companion_writeback_enabled: { description: "回流直播事件到陪伴插件", type: "bool", default: true },
  private_companion_viewer_activity_enabled: { description: "记录直播观众活跃画像", type: "bool", default: true },
  private_companion_viewer_activity_context_enabled: { description: "注入观众活跃画像", type: "bool", default: true },
  private_companion_auto_register_viewers: { description: "自动登记直播观众", type: "bool", default: true },
  private_companion_auto_register_min_events: { description: "自动登记最少互动次数", type: "int", default: 2, slider: { min: 1, max: 20, step: 1 } },
  private_companion_live_state_enabled: { description: "直播互动影响当日状态", type: "bool", default: true },
  private_companion_live_state_cooldown_seconds: { description: "直播状态影响冷却", type: "float", default: 300, slider: { min: 30, max: 1800, step: 30 } },
  private_companion_live_state_duration_hours: { description: "直播状态余韵持续小时", type: "int", default: 2, slider: { min: 1, max: 12, step: 1 } },
  private_companion_live_summary_enabled: { description: "下播生成直播小结", type: "bool", default: true },

  subtitle_enabled: { description: "启用打字机字幕 overlay", type: "bool", default: false },
  subtitle_scope: { description: "打字机字幕触发范围", type: "string", default: "bili_live", options: ["bili_live", "all"] },
  subtitle_host: { description: "字幕服务监听地址", type: "string", default: "127.0.0.1" },
  subtitle_port: { description: "字幕服务端口", type: "int", default: 18081 },
  subtitle_typing_speed_ms: { description: "打字速度（毫秒/字）", type: "int", default: 45, slider: { min: 5, max: 200, step: 5 } },
  subtitle_hold_seconds: { description: "字幕停留时间（秒）", type: "float", default: 4, slider: { min: 0, max: 30, step: 0.5 } },
  subtitle_max_length: { description: "字幕最大长度", type: "int", default: 120, slider: { min: 0, max: 500, step: 10 } },
  subtitle_font_size: { description: "字幕字号", type: "int", default: 42, slider: { min: 16, max: 96, step: 2 } },
  subtitle_font_weight: { description: "字幕字重", type: "int", default: 700 },
  subtitle_text_color: { description: "字幕颜色", type: "string", default: "#ffffff" },
  subtitle_stroke_color: { description: "字幕描边颜色", type: "string", default: "#111111" },
  subtitle_stroke_size: { description: "字幕描边大小", type: "int", default: 4, slider: { min: 0, max: 12, step: 1 } },
  subtitle_cursor_color: { description: "打字光标颜色", type: "string", default: "#ffffff" },
  subtitle_show_cursor: { description: "显示打字光标", type: "bool", default: true },
  subtitle_fade_out: { description: "字幕结束时淡出", type: "bool", default: true },
  subtitle_position: { description: "字幕位置", type: "string", default: "bottom", options: ["bottom", "center", "top"] },
  subtitle_padding: { description: "字幕边距", type: "int", default: 48, slider: { min: 0, max: 200, step: 4 } },
  subtitle_max_width: { description: "字幕最大宽度", type: "int", default: 1100, slider: { min: 300, max: 1920, step: 20 } },
  subtitle_strip_l2d_tags: { description: "字幕清理 L2D 标签", type: "bool", default: true },
  subtitle_strip_tts_blocks: { description: "字幕移除 TTS 语音段", type: "bool", default: true },
  subtitle_voice_use_following_plain: { description: "语音消息只显示后续文本", type: "bool", default: true },
  subtitle_prefer_chinese_text: { description: "字幕优先提取中文", type: "bool", default: true },
  subtitle_use_tts_spoken_text: { description: "直播 TTS 字幕显示朗读文本", type: "bool", default: false },
  subtitle_strip_html_tags: { description: "字幕清理尖括号标签", type: "bool", default: true },

  mouth_sync_enabled: { description: "启用 TTS 语音嘴型联动", type: "bool", default: false },
  mouth_sync_open_parameter: { description: "嘴部开闭参数", type: "string", default: "MouthOpen" },
  mouth_sync_form_parameter: { description: "嘴型变形参数（可选）", type: "string", default: "" },
  mouth_sync_fps: { description: "嘴型更新帧率", type: "int", default: 30, slider: { min: 5, max: 60, step: 1 } },
  mouth_sync_gain: { description: "嘴型音量增益", type: "float", default: 1.6, slider: { min: 0.1, max: 5, step: 0.1 } },
  mouth_sync_smoothing: { description: "嘴型平滑", type: "float", default: 0.45, slider: { min: 0, max: 0.95, step: 0.05 } },
  mouth_sync_noise_gate: { description: "静音阈值", type: "float", default: 0.03, slider: { min: 0, max: 0.3, step: 0.01 } },
  mouth_sync_form_strength: { description: "嘴型变形强度", type: "float", default: 0.18, slider: { min: 0, max: 1, step: 0.05 } },
  mouth_sync_mode: { description: "参数注入模式", type: "string", default: "set", options: ["set", "add"] },
};



